### ISSUE TITLE
Timeout setup ?

### ISSUE THREAD

**Issue by ServeurpersoCom** [MajenkoLibraries/Watchdog#1]
Hi dear Matt,

I look for PIC32/ChipKit watchdog on google and I found Majenko. lol

I need to watch my 40Hz PID loop, if the code freeze the robot must stop (reset uC).

I need 50 or 100mS kick timeout before reset and not the board default of 17 minutes lol, Where is the timeout setup I can't find inside your code ?

**Comment by majenkotech** [comment]
That's because it isn't inside my code. And no, it's not an oversight on my part.

You can't change the timeout - it's set in the configuration bits of the chip. You would need to compile a new bootloader with the new settings in and flash it to the chip.

**Comment by ServeurpersoCom** [comment]
I have the ICD3 to flash the bootloader not a problem. I use the ChipKit bootloader because I need UART for flashing

I need a solution to low the PWM on my robot if there is a divide by zero or infinite loop in my code

the watchdog is the best / only choice a think (without external hardware).
